//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityExample
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbStudentEntities : DbContext
    {
        public DbStudentEntities()
            : base("name=DbStudentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClassTable> ClassTables { get; set; }
        public virtual DbSet<StudentTable> StudentTables { get; set; }
        public virtual DbSet<TableGrade> TableGrades { get; set; }
    
        public virtual ObjectResult<GRADELIST_Result> GRADELIST()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GRADELIST_Result>("GRADELIST");
        }
    }
}
